version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - go-server

  go-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

networks:
  default:
    driver: bridge
