# Utiliser une image Go officielle comme image de base
FROM golang:1.23-alpine

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers go.mod et go.sum et installer les dépendances
COPY go.mod go.sum ./
RUN go mod download

# Copier tous les fichiers du projet dans le conteneur
COPY . .

# Construire le serveur Go
RUN go build -o server

# Exposer le port 8080
EXPOSE 8080

# Démarrer le serveur
CMD ["./server"]
